/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const CateringInquiry = IDL.Record({
  'id' : IDL.Nat,
  'guestCount' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
  'phone' : IDL.Text,
  'eventDate' : IDL.Text,
});
export const ContactInquiry = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
  'phone' : IDL.Text,
});
export const Category = IDL.Variant({
  'MishtiDoi' : IDL.Null,
  'Barfi' : IDL.Null,
  'Laddoo' : IDL.Null,
  'Chamcham' : IDL.Null,
  'Rasgulla' : IDL.Null,
  'Sandesh' : IDL.Null,
});
export const Sweet = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imagePlaceholder' : IDL.Text,
  'category' : Category,
  'price' : IDL.Text,
  'ingredients' : IDL.Vec(IDL.Text),
  'occasions' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'getAllCateringInquiries' : IDL.Func(
      [],
      [IDL.Vec(CateringInquiry)],
      ['query'],
    ),
  'getAllContactInquiries' : IDL.Func([], [IDL.Vec(ContactInquiry)], ['query']),
  'getAllSweets' : IDL.Func([], [IDL.Vec(Sweet)], ['query']),
  'getSweetById' : IDL.Func([IDL.Nat], [IDL.Opt(Sweet)], ['query']),
  'getSweetsByCategory' : IDL.Func([Category], [IDL.Vec(Sweet)], ['query']),
  'submitCateringInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitContactInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const CateringInquiry = IDL.Record({
    'id' : IDL.Nat,
    'guestCount' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
    'phone' : IDL.Text,
    'eventDate' : IDL.Text,
  });
  const ContactInquiry = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
    'phone' : IDL.Text,
  });
  const Category = IDL.Variant({
    'MishtiDoi' : IDL.Null,
    'Barfi' : IDL.Null,
    'Laddoo' : IDL.Null,
    'Chamcham' : IDL.Null,
    'Rasgulla' : IDL.Null,
    'Sandesh' : IDL.Null,
  });
  const Sweet = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imagePlaceholder' : IDL.Text,
    'category' : Category,
    'price' : IDL.Text,
    'ingredients' : IDL.Vec(IDL.Text),
    'occasions' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'getAllCateringInquiries' : IDL.Func(
        [],
        [IDL.Vec(CateringInquiry)],
        ['query'],
      ),
    'getAllContactInquiries' : IDL.Func(
        [],
        [IDL.Vec(ContactInquiry)],
        ['query'],
      ),
    'getAllSweets' : IDL.Func([], [IDL.Vec(Sweet)], ['query']),
    'getSweetById' : IDL.Func([IDL.Nat], [IDL.Opt(Sweet)], ['query']),
    'getSweetsByCategory' : IDL.Func([Category], [IDL.Vec(Sweet)], ['query']),
    'submitCateringInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitContactInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };