/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'MishtiDoi' : null } |
  { 'Barfi' : null } |
  { 'Laddoo' : null } |
  { 'Chamcham' : null } |
  { 'Rasgulla' : null } |
  { 'Sandesh' : null };
export interface CateringInquiry {
  'id' : bigint,
  'guestCount' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Timestamp,
  'phone' : string,
  'eventDate' : string,
}
export interface ContactInquiry {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Timestamp,
  'phone' : string,
}
export interface Sweet {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'imagePlaceholder' : string,
  'category' : Category,
  'price' : string,
  'ingredients' : Array<string>,
  'occasions' : Array<string>,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'getAllCateringInquiries' : ActorMethod<[], Array<CateringInquiry>>,
  'getAllContactInquiries' : ActorMethod<[], Array<ContactInquiry>>,
  'getAllSweets' : ActorMethod<[], Array<Sweet>>,
  'getSweetById' : ActorMethod<[bigint], [] | [Sweet]>,
  'getSweetsByCategory' : ActorMethod<[Category], Array<Sweet>>,
  'submitCateringInquiry' : ActorMethod<
    [string, string, string, string, bigint, string],
    bigint
  >,
  'submitContactInquiry' : ActorMethod<
    [string, string, string, string],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];