/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Sweet {
    id: bigint;
    name: string;
    description: string;
    imagePlaceholder: string;
    category: Category;
    price: string;
    ingredients: Array<string>;
    occasions: Array<string>;
}
export type Timestamp = bigint;
export interface ContactInquiry {
    id: bigint;
    name: string;
    email: string;
    message: string;
    timestamp: Timestamp;
    phone: string;
}
export interface CateringInquiry {
    id: bigint;
    guestCount: bigint;
    name: string;
    email: string;
    message: string;
    timestamp: Timestamp;
    phone: string;
    eventDate: string;
}
export enum Category {
    MishtiDoi = "MishtiDoi",
    Barfi = "Barfi",
    Laddoo = "Laddoo",
    Chamcham = "Chamcham",
    Rasgulla = "Rasgulla",
    Sandesh = "Sandesh"
}
export interface backendInterface {
    getAllCateringInquiries(): Promise<Array<CateringInquiry>>;
    getAllContactInquiries(): Promise<Array<ContactInquiry>>;
    getAllSweets(): Promise<Array<Sweet>>;
    getSweetById(id: bigint): Promise<Sweet | null>;
    getSweetsByCategory(category: Category): Promise<Array<Sweet>>;
    submitCateringInquiry(name: string, email: string, phone: string, eventDate: string, guestCount: bigint, message: string): Promise<bigint>;
    submitContactInquiry(name: string, email: string, phone: string, message: string): Promise<bigint>;
}
import type { Category as _Category, Sweet as _Sweet } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllCateringInquiries(): Promise<Array<CateringInquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCateringInquiries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCateringInquiries();
            return result;
        }
    }
    async getAllContactInquiries(): Promise<Array<ContactInquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContactInquiries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContactInquiries();
            return result;
        }
    }
    async getAllSweets(): Promise<Array<Sweet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSweets();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSweets();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSweetById(arg0: bigint): Promise<Sweet | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSweetById(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSweetById(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSweetsByCategory(arg0: Category): Promise<Array<Sweet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSweetsByCategory(to_candid_Category_n7(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSweetsByCategory(to_candid_Category_n7(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitCateringInquiry(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitCateringInquiry(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitCateringInquiry(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async submitContactInquiry(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactInquiry(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactInquiry(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_Category_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Sweet_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Sweet): Sweet {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Sweet]): Sweet | null {
    return value.length === 0 ? null : from_candid_Sweet_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    description: string;
    imagePlaceholder: string;
    category: _Category;
    price: string;
    ingredients: Array<string>;
    occasions: Array<string>;
}): {
    id: bigint;
    name: string;
    description: string;
    imagePlaceholder: string;
    category: Category;
    price: string;
    ingredients: Array<string>;
    occasions: Array<string>;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        imagePlaceholder: value.imagePlaceholder,
        category: from_candid_Category_n4(_uploadFile, _downloadFile, value.category),
        price: value.price,
        ingredients: value.ingredients,
        occasions: value.occasions
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    MishtiDoi: null;
} | {
    Barfi: null;
} | {
    Laddoo: null;
} | {
    Chamcham: null;
} | {
    Rasgulla: null;
} | {
    Sandesh: null;
}): Category {
    return "MishtiDoi" in value ? Category.MishtiDoi : "Barfi" in value ? Category.Barfi : "Laddoo" in value ? Category.Laddoo : "Chamcham" in value ? Category.Chamcham : "Rasgulla" in value ? Category.Rasgulla : "Sandesh" in value ? Category.Sandesh : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Sweet>): Array<Sweet> {
    return value.map((x)=>from_candid_Sweet_n2(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    MishtiDoi: null;
} | {
    Barfi: null;
} | {
    Laddoo: null;
} | {
    Chamcham: null;
} | {
    Rasgulla: null;
} | {
    Sandesh: null;
} {
    return value == Category.MishtiDoi ? {
        MishtiDoi: null
    } : value == Category.Barfi ? {
        Barfi: null
    } : value == Category.Laddoo ? {
        Laddoo: null
    } : value == Category.Chamcham ? {
        Chamcham: null
    } : value == Category.Rasgulla ? {
        Rasgulla: null
    } : value == Category.Sandesh ? {
        Sandesh: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
